MOV A,#55H // MOVE THE IMMEDIAT ADDRESS 55H TO THE ACCUNALETER A
MOV R2,#26H	 // MOVE THE IMMEDIATE ADDTESS TO THE RESITER R2
MOV R1,#10H	// MOVE THE IMMEDIATE ADDRESS 10H TO THE RESITER R1

LOOP1:    	//LOOP1 ONE IS EXCUTED 26 TIMES 
LOOP2:     //   LOOP2 TWO IS EXCUTED 10 TIMES 
CPL A		//COMPLIMENT THE ACCUMALETER CONTENT TOTEL 260 TIMES 26X10 =260
DJNZ R1,LOOP2  // DECREMENT AND JUMP IF R1 NOT EQUAL TO ZERO AND JUMP TO THE LOOP2 SETEMENT
DJNZ R2,LOOP1  // DECERMENT AND JUMP IF R2 NOT EQUAL TO ZERO AND JUMP TO THE LOOP1 SETMENT
END				// END THE PROGRAM


TRACE:
A=55H
R2=26H
R1=10H

LOOP1:
COMPLIMENT: A=A' 
DECREMET AND JUMP IF NOT EQUAL: R1 LOOP1 (THIS LOOP1 IS EXECUTED 10 TIMES)
DECEMENT AND JUMP IF NOT EQUAL: R2 LOOP2 ()THIS LOOP2 IS EXECUTED 26 TIMES)
THERFORE:CPL A THIS STETMENT IS EXECUTED 26*10=260 TIMES


 